
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1093382
	#The name of the modpack
	modpackName = "Society: Sunlit Valley"
	#The version of the modpack
	modpackVersion = "4.0.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

