#Ignore serializer error and load the game anyway
ignore_serializer_error = false
#Only show serializer errors
only_show_errors = true
#Re-order client IDs
reorder_client_ids = true
#Suppress re-order logging
suppress_reorder_logging = true

